### PR TITLE
chore: use renovate-presets-jvm to group updates

### PR DESCRIPTION
**Pull request by robstoll**
More an excuse to open a PR. I was skimming through projects on GitHub using Atrium and found also this one. 
We can include it in the README of Atrium as third-party extension if you like.

### CODE REVIEW

**Comment by jGleitz** [comment]
Thanks for the PR!

**Comment by jGleitz** [comment]
> We can include it in the README of Atrium as third-party extension if you like.

Gladly!

**Comment by jGleitz** [comment]
@robstoll do you plan to contribute this configuration upstream? Renovate is usually welcoming such improvements!

**Comment by robstoll** [comment]
> Gladly!

Done

> do you plan to contribute this configuration upstream? 

Was my first plan. I don't remember why I did it in an own repo in the end but I have something in mind that it was too cumbersome to contribute.

**Comment by jGleitz** [comment]
> it was too cumbersome to contribute.

If you don’t mind, I’d create a PR if I find the time.

**Pull request merged**
